### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by Ivan-Despot** [TariqAHassan/SurveyExplorer#1]
The app created by Tariq Hassan allows the user to cluster mental health data between different regions of the world and age range. Overall, the app was intuitive, and I appreciate the clean and simple clustering graph displayed. I found the summary statistics also helpful. There was an issue with an error that was due to having selected `ALL` and then trying to search for a subset (`California`, `Oregon`). The weighting for the survey questions was also a very useful feature of this app. Initially, it took some time to read and understand the survey questions and their corresponding codes. Also, I feel as if the app was targeted towards an audience that understands clustering and PCA (I cannot recall if there was a brief explanation for what the axis represented etc). Furthermore, I feel like a few more aesthetics could be added? Perhaps consider an infoBox or valueBox from the package `shinydashboard` or implement some more visuals with `shinywidgets`. Overall, I was very impressed with the scope of the app and the many challenges that likely had to be overcome to implement an application of this magnitude.

Recap:

* Error when the user selects all and then selects a subset of countries at the same time.

* Consider further simplifying the annotations for the survey questions or PCA components.

* Aesthetics

**Comment by TariqAHassan** [comment]
Thanks
