### ISSUE TITLE
Feedback from Session 2

### ISSUE THREAD

**Issue by TeddTech** [TariqAHassan/SurveyExplorer#2]
This app is a tool that provides a way to assess the mental health of workers in the technology industry. The app provides a choice of method of analysis between kmeans and summary statistics. The app includes many locations which you can include or exclude from you're analysis if you wish too. There is much variety in types of questions available. The analysis itself can be customized by changing the weight of a question. 

Overall this app is very well done.  The design could be improved in terms of real estate. It is understood that the text at the bottom of the display is there to define the terms used in survey questions but it may distract from what the plots are attempting to convey. I also found that the **Survey Questions Weighting (Advanced)** may cause the user to exert more effort than necessary when using the app. To make the interface more user-friendly one suggestion would be to remove  **Survey Questions Weighting (Advanced)** section. Again very well done, eager to see the final version.

**Comment by TariqAHassan** [comment]
Thanks
